'use strict';
const APP_VERSION='1.0.0';
const $=id=>document.getElementById(id);
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const same=(a,b)=>iso(a)===iso(b);
const esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[x]));
const dateFrom=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d,12);};
const fullDate=d=>new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',year:'numeric'}).format(d);
let now=new Date(), selectedDate=new Date(now.getFullYear(),now.getMonth(),now.getDate(),12), monthDate=new Date(now.getFullYear(),now.getMonth(),1,12);
const STORE='bbm-pwa-v1';
function normalise(raw){const ids=new Set(rituals.map(r=>r.id));return {favorites:[...new Set((Array.isArray(raw?.favorites)?raw.favorites:[]).filter(id=>ids.has(id)))],log:(Array.isArray(raw?.log)?raw.log:[]).filter(x=>ids.has(x?.id)&&/^\d{4}-\d{2}-\d{2}$/.test(x?.date)&&Number.isFinite(x?.ts)),settings:{largeText:raw?.settings?.largeText===true,showPhase:raw?.settings?.showPhase!==false},onboarded:raw?.onboarded===true};}
function load(){try{const current=localStorage.getItem(STORE);if(current)return normalise(JSON.parse(current));return normalise(JSON.parse(localStorage.getItem('bbm-v5')||'{}'));}catch{return normalise({});}}
let state=load(), search='', category='all', currentId=null, originFocus=null, deferredInstall=null, swRegistration=null, toastTimer;
function persist(){try{localStorage.setItem(STORE,JSON.stringify(state));return true;}catch{toast('Телефон не сохранил данные. Проверьте свободное место и приватный режим.');return false;}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4200);}
const isDone=id=>state.log.some(x=>x.id===id&&x.date===iso(now));
function done(id){if(isDone(id))return;const old=state.log;state.log=[...old,{id,date:iso(now),ts:Date.now()}];if(!persist()){state.log=old;return;}toast('Поколдовано. Вселенная получила входящее.');render();if(currentId)renderDetail();}
function favorite(id){const old=state.favorites;state.favorites=old.includes(id)?old.filter(x=>x!==id):[...old,id];if(!persist()){state.favorites=old;return;}render();if(currentId)renderDetail();toast(state.favorites.includes(id)?'Сохранено в «Моё»':'Убрано из сохранённого');}
function card(r,complete=true){return `<article class="ritual-card"><div class="card-top"><span class="glyph" aria-hidden="true">${esc(r.icon)}</span><div><button class="title-btn" data-open="${r.id}">${esc(r.title)}</button><div class="meta">${esc(r.when)} · ${esc(r.cat.map(c=>CAT[c].n).join(' / '))}</div></div></div><p>${esc(r.short)}</p><div class="actions"><button data-open="${r.id}">Как это делается</button>${complete?`<button class="primary" data-done="${r.id}" ${isDone(r.id)?'disabled':''}>${isDone(r.id)?'✓ Поколдовано':'Поколдовано'}</button>`:''}<button class="save-small" data-save="${r.id}" aria-label="${state.favorites.includes(r.id)?'Убрать из сохранённого':'Сохранить'}: ${esc(r.title)}" aria-pressed="${state.favorites.includes(r.id)}">${state.favorites.includes(r.id)?'♥':'♡'}</button></div></article>`;}
function nextEvent(d){for(let i=1;i<=370;i++){const day=new Date(d.getFullYear(),d.getMonth(),d.getDate()+i,12);const list=scheduledForDate(day).filter(r=>!['waxing','waning'].includes(r.rule));if(list.length)return {day,list};}return null;}
function summary(){const list=scheduledForDate(now).filter(r=>!['waxing','waning'].includes(r.rule));return {title:list.length?'У Вселенной есть поручения.':'Срочных чар не поступало.',text:list.length?`На сегодня: ${list.map(r=>r.title).join(' · ')}. Можно без героизма — начните с одного.`:'Календарь не требует реквизита. Обычные дела тоже считаются делами.',list};}
function todayPage(){const s=summary(), next=nextEvent(now), phaseList=scheduledForDate(now).filter(r=>['waxing','waning'].includes(r.rule));return `${!state.onboarded?'<div class="onboarding"><strong>Ваш маленький отдел бытовых чудес.</strong><p class="muted">Сохраняйте приметы и отмечайте «Поколдовано». Журнал остаётся на этом устройстве.</p><button data-action="onboard">Ладно, начинаем</button></div>':''}<span class="eyebrow">${esc(new Intl.DateTimeFormat('ru-RU',{weekday:'long'}).format(now))} / ${esc(fullDate(now))}</span><section class="hero"><span class="stamp">ВСЁ НЕМНОГО СТРАННО</span><h1>${s.title}</h1><p>${esc(s.text)}</p><button data-action="share-day">Поделиться сводкой</button></section><div class="section-head"><h2>По расписанию</h2><span class="count">${s.list.length} сегодня</span></div>${s.list.length?s.list.map(r=>card(r)).join(''):'<div class="empty"><h3>Никаких дедлайнов от космоса.</h3><p>Можно выбрать примету в библиотеке или просто прожить день.</p><a href="#rituals">Открыть ритуалы</a></div>'}${state.settings.showPhase?`<div class="section-head"><h2>На этой фазе Луны</h2><span aria-hidden="true">${moonAt(now).icon}</span></div><p class="phase-note">${esc(moonAt(now).name)}. Эти практики актуальны несколько дней, а не только сегодня.</p>${phaseList.map(r=>card(r)).join('')}`:''}${next?`<div class="section-head"><h2>Следующее по плану</h2></div><button class="next" data-date="${iso(next.day)}"><span class="eyebrow">${fullDate(next.day)}</span><strong>${esc(next.list[0].title)}</strong><span>${next.list.length>1?`И ещё ${next.list.length-1}. `:''}Посмотреть этот день</span></button>`:''}`;}
function calendarPage(){const y=monthDate.getFullYear(),m=monthDate.getMonth(),offset=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate();let cells=['ПН','ВТ','СР','ЧТ','ПТ','СБ','ВС'].map(d=>`<div class="weekday">${d}</div>`).join('')+'<div></div>'.repeat(offset);for(let i=1;i<=days;i++){const d=new Date(y,m,i,12),all=scheduledForDate(d),fixed=all.filter(r=>!['waxing','waning'].includes(r.rule));cells+=`<button class="day ${fixed.length?'event':''} ${all.length>fixed.length?'phase':''} ${same(d,now)?'today':''} ${same(d,selectedDate)?'selected':''}" data-select="${iso(d)}" aria-label="${fullDate(d)}${same(d,now)?', сегодня':''}, ритуалов: ${all.length}" aria-pressed="${same(d,selectedDate)}">${i}</button>`;}const selected=scheduledForDate(selectedDate);return `<span class="eyebrow">ДАТЫ С ПОДТЕКСТОМ</span><h1>Календарь</h1><div class="monthbar"><button class="icon-btn" data-month="-1" aria-label="Предыдущий месяц">‹</button><strong>${new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(monthDate)}</strong><button class="icon-btn" data-month="1" aria-label="Следующий месяц">›</button></div><button data-action="calendar-today">К сегодняшнему дню</button><div class="calendar">${cells}</div><p class="legend">Оранжевая точка — событие по расписанию. Синяя — практика лунной фазы. Розовый контур — сегодня.</p><h2>${fullDate(selectedDate)}</h2>${selected.length?selected.map(r=>card(r,same(selectedDate,now))).join(''):'<div class="empty">На эту дату ничего не назначено. Библиотека открыта всегда.</div>'}<p class="muted">Лунные даты рассчитываются приблизительно, в часовом поясе устройства. Исходный алгоритм проекта сохранён.</p>`;}
function libraryPage(){return `<span class="eyebrow">РЕКВИЗИТ И ПРОТОКОЛЫ</span><h1>Ритуалы</h1><label class="eyebrow" for="search">Поиск по названию и реквизиту</label><input class="search" id="search" type="search" placeholder="Корица, кошелёк, любовь…" value="${esc(search)}"><div class="filters" aria-label="Категории">${[{id:'all',n:'Все'},...Object.entries(CAT).map(([id,c])=>({id,n:c.n}))].map(c=>`<button data-category="${c.id}" class="${category===c.id?'active':''}" aria-pressed="${category===c.id}">${c.n}</button>`).join('')}</div><div id="libraryResults"></div>`;}
function renderLibrary(){const q=search.trim().toLocaleLowerCase('ru');const list=rituals.filter(r=>(category==='all'||r.cat.includes(category))&&[r.title,r.short,r.need,...r.cat.map(c=>CAT[c].n)].join(' ').toLocaleLowerCase('ru').includes(q));$('libraryResults').innerHTML=`<p class="count" aria-live="polite">Найдено: ${list.length} из ${rituals.length}</p>`+(list.length?list.map(r=>card(r)).join(''):'<div class="empty">Такого реквизита у Вселенной нет. Попробуйте другое слово или категорию.</div>');}
function minePage(){const monthly=state.log.filter(x=>x.date.startsWith(iso(now).slice(0,7)));const unique=new Set(state.log.map(x=>x.id)).size;const badge=monthly.length===0?'Пока наблюдаем за космосом.':monthly.length<5?'Бытовая магия вышла на смену.':'Отдел странных дел работает регулярно.';return `<span class="eyebrow">ЛОКАЛЬНЫЙ АРХИВ ЧУДЕС</span><h1>Моё</h1><p>${badge}</p><div class="stats"><div class="stat"><b>${monthly.length}</b><span>«Поколдовано» за ${new Intl.DateTimeFormat('ru-RU',{month:'long'}).format(now)}</span></div><div class="stat"><b>${unique}</b><span>ритуалов попробовано</span></div></div><div class="section-head"><h2>Сохранённое</h2><span class="count">${state.favorites.length}</span></div>${state.favorites.length?state.favorites.map(id=>card(rituals.find(r=>r.id===id))).join(''):'<div class="empty">Нажмите сердечко у ритуала — он будет ждать здесь.</div>'}<div class="section-head"><h2>Поколдовано</h2><span class="count">${state.log.length} всего</span></div>${state.log.length?[...state.log].sort((a,b)=>b.ts-a.ts).map(x=>`<div class="history-row"><div><button class="title-btn" style="font-size:17px" data-open="${x.id}">${esc(rituals.find(r=>r.id===x.id).title)}</button><small>${fullDate(dateFrom(x.date))}</small></div><button data-undo="${x.ts}" data-id="${x.id}" aria-label="Отменить отметку: ${esc(rituals.find(r=>r.id===x.id).title)}">Отменить</button></div>`).join(''):'<div class="empty">История начнётся с первого «Поколдовано».</div>'}<div class="section-head"><h2>Настройки</h2></div><div class="settings"><label><input type="checkbox" data-setting="showPhase" ${state.settings.showPhase?'checked':''}>Практики лунной фазы на главном</label><label><input type="checkbox" data-setting="largeText" ${state.settings.largeText?'checked':''}>Увеличить текст описаний</label><button data-action="install">${standalone()?'Как установлено приложение':'На главный экран телефона'}</button><button data-action="export">Скачать копию моего журнала</button><button data-action="check-update">Проверить обновление</button><p id="offlineStatus" class="offline-status">Проверяем запас для работы без сети…</p><p class="muted">Версия ${APP_VERSION}. Данные хранятся только в этом браузере на этом устройстве. Между preview и production журнал не переносится автоматически. Удаление данных сайта может удалить журнал.</p></div>`;}
function currentTab(){const hash=location.hash.slice(1);return ['today','calendar','rituals','mine'].includes(hash)?hash:'today';}
function render(){const tab=currentTab();document.body.classList.toggle('large-text',state.settings.largeText);$('main').innerHTML=({today:todayPage,calendar:calendarPage,rituals:libraryPage,mine:minePage})[tab]();document.querySelectorAll('[data-tab]').forEach(a=>{if(a.dataset.tab===tab)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});if(tab==='rituals')renderLibrary();if(tab==='mine')offlineStatus();}
function renderDetail(){const r=rituals.find(x=>x.id===currentId);if(!r)return;const steps=r.steps||r.do.split(/(?<=[.!?])\s+(?=[А-ЯЁ])/).filter(Boolean);$('detailBody').innerHTML=`<span class="eyebrow">№ ${r.no} / ${esc(OR[r.origin])}</span><h2>${esc(r.title)}</h2><p>${esc(r.short)}</p><div class="block"><span class="eyebrow">Когда</span><p>${esc(r.when)}</p></div><div class="block"><span class="eyebrow">Что понадобится</span><p>${esc(r.need)}</p></div><div class="block"><span class="eyebrow">Что делать</span><ol>${steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></div><div class="block"><span class="eyebrow">Что говорить</span><p>${esc(r.say)}</p></div><p class="muted">${esc(r.cat.map(c=>CAT[c].n).join(' / '))}. ${esc(OR[r.origin])} — классификация из исходного проекта.</p><div class="actions"><button data-save="${r.id}" aria-pressed="${state.favorites.includes(r.id)}">${state.favorites.includes(r.id)?'♥ Сохранено':'♡ Сохранить'}</button><button data-share="${r.id}">Поделиться</button><button class="primary" data-done="${r.id}" ${isDone(r.id)?'disabled':''}>${isDone(r.id)?'✓ Поколдовано':'Поколдовано'}</button></div><p class="muted">Отметка относится к сегодняшнему дню.</p>`;}
function openDetail(id){if(!rituals.some(r=>r.id===id))return;originFocus=document.activeElement;currentId=id;renderDetail();if(!$('detail').open)$('detail').showModal();}
function closeDetail(){if($('detail').open)$('detail').close();currentId=null;}
$('detail').addEventListener('close',()=>{currentId=null;originFocus?.isConnected&&originFocus.focus();if(location.hash.startsWith('#ritual-'))history.replaceState(null,'','#today');});
function standalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;}
function installInstructions(){const ios=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);$('installBody').innerHTML=standalone()?'<p>Приложение уже открыто отдельно от браузера. Добро пожаловать домой.</p>':ios?'<p>Сейчас сделай это: открой эту ссылку в Safari.</p><ol><li>Нажми «Поделиться» (квадрат со стрелкой вверх).</li><li>Выбери «На экран Домой».</li><li>Если доступен переключатель «Открывать как веб-приложение», включи его. Нажми «Добавить».</li><li>Закрой Safari и открой «Бытовую магию» по новой иконке.</li></ol>':`${deferredInstall?'<button class="primary" data-action="native-install">Установить приложение</button>':'<p>Если браузер ещё не предлагает установку, открой его меню и найди «Установить приложение» или «Добавить на главный экран».</p>'}<p>На Android лучше открыть ссылку в Chrome. Во встроенном браузере Telegram или другой соцсети сначала выбери «Открыть в браузере».</p><p class="muted">На компьютере установка доступна в поддерживающих PWA браузерах. Если пункта установки нет, можно продолжить по ссылке.</p>`;$('install').showModal();}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;});window.addEventListener('appinstalled',()=>{deferredInstall=null;toast('Магия переехала на главный экран');});
async function shareData(data){try{if(navigator.share){await navigator.share(data);return;}}catch(e){if(e.name==='AbortError')return;}const text=`${data.text}\n${data.url}`;try{await navigator.clipboard.writeText(text);toast('Текст и ссылка скопированы');}catch{$('shareText').value=text;$('shareFallback').showModal();$('shareText').select();}}
async function offlineStatus(){try{const cache=await caches.open('bbm-shell-'+APP_VERSION);const ready=await cache.match(new URL('./rituals.js',location.href).href);const node=$('offlineStatus');if(node)node.textContent=ready?'Запас загружен: интерфейс и ритуалы доступны без сети.':'Для offline нужно дождаться первой загрузки с интернетом.';}catch{if($('offlineStatus'))$('offlineStatus').textContent='Браузер не подтвердил offline-кеш.';}}
$('closeDetail').onclick=closeDetail;$('closeInstall').onclick=()=>$('install').close();$('closeShare').onclick=()=>$('shareFallback').close();$('copyShare').onclick=async()=>{try{await navigator.clipboard.writeText($('shareText').value);toast('Скопировано');$('shareFallback').close();}catch{$('shareText').select();toast('Выделенный текст можно скопировать вручную');}};
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const d=b.dataset;if(d.open)openDetail(d.open);if(d.done)done(d.done);if(d.save)favorite(d.save);if(d.share){const r=rituals.find(r=>r.id===d.share);shareData({title:r.title,text:`Бытовая магия: ${r.title}. ${r.short}`,url:new URL(`#ritual-${r.id}`,location.href).href});}if(d.date){selectedDate=dateFrom(d.date);monthDate=new Date(selectedDate.getFullYear(),selectedDate.getMonth(),1,12);location.hash='calendar';}if(d.select){selectedDate=dateFrom(d.select);render();document.querySelector(`[data-select="${d.select}"]`)?.focus();}if(d.month){monthDate=new Date(monthDate.getFullYear(),monthDate.getMonth()+Number(d.month),1,12);selectedDate=new Date(monthDate);render();document.querySelector(`[data-month="${d.month}"]`)?.focus();}if(d.category){category=d.category;render();document.querySelector(`[data-category="${category}"]`)?.focus();}if(d.undo){const old=state.log;state.log=old.filter(x=>!(x.ts===Number(d.undo)&&x.id===d.id));if(!persist())state.log=old;render();}switch(d.action){case'onboard':state.onboarded=true;persist();render();break;case'install':installInstructions();break;case'native-install':if(deferredInstall){await deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('install').close();}break;case'share-day':{const s=summary();shareData({title:'Бытовая магия — сегодня',text:`${fullDate(now)}. ${s.title} ${s.text}`,url:new URL('#today',location.href).href});break;}case'calendar-today':selectedDate=new Date(now);monthDate=new Date(now.getFullYear(),now.getMonth(),1,12);render();break;case'export':{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`bytovaya-magiya-${iso(now)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);break;}case'check-update':try{if(!swRegistration){toast('Offline ещё не подготовлен. Откройте приложение с интернетом.');break;}await swRegistration.update();toast(swRegistration.waiting?'Новая версия готова — нажмите «Обновить»':'Проверка завершена. Если версия появится, сверху будет кнопка.');}catch{toast('Сейчас проверить обновление не получилось');}break;}});
document.addEventListener('input',e=>{if(e.target.id==='search'){search=e.target.value;renderLibrary();}});document.addEventListener('change',e=>{const key=e.target.dataset.setting;if(key){const old=state.settings[key];state.settings[key]=e.target.checked;if(!persist())state.settings[key]=old;render();document.querySelector(`[data-setting="${key}"]`)?.focus();}});
function route(){closeDetail();render();if(location.hash.startsWith('#ritual-'))openDetail(location.hash.slice(8));window.scrollTo(0,0);}
window.addEventListener('hashchange',route);
function refreshDate(){const old=iso(now);now=new Date();if(old!==iso(now)){selectedDate=new Date(now);monthDate=new Date(now.getFullYear(),now.getMonth(),1,12);render();if(currentId)renderDetail();}}
document.addEventListener('visibilitychange',()=>{if(!document.hidden){refreshDate();swRegistration?.update().catch(()=>{});}});setInterval(refreshDate,30000);window.addEventListener('storage',e=>{if(e.key===STORE){state=load();render();if(currentId)renderDetail();}});
function connection(){$('connection').hidden=navigator.onLine;}window.addEventListener('online',connection);window.addEventListener('offline',connection);connection();route();
if('serviceWorker' in navigator){let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(refreshing)location.reload();});navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(reg=>{swRegistration=reg;const showUpdate=()=>{if(reg.waiting&&navigator.serviceWorker.controller){$('update').hidden=false;$('applyUpdate').onclick=()=>{refreshing=true;reg.waiting?.postMessage({type:'SKIP_WAITING'});};}};showUpdate();reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'){showUpdate();offlineStatus();}});});navigator.serviceWorker.ready.then(()=>offlineStatus());}).catch(()=>toast('Offline пока не подготовлен. Попробуйте ещё раз с интернетом.'));}
